### PR TITLE
Implement gh actions using tag commit message to build docker images

### PR DESCRIPTION
**Pull request by mrceyhun**
This PR implements GH actions to build our docker images that use CMSSpark repository mainly. Currently we can build docker images of:
- cmsmon-rudico-ds
- cmsmon-rucio-spark2mng
- condor-cpu-eff

`registry.cern.ch/cmsmonitoring/cmsmon-hadoop-base` image will be used as base image in these images. We cannot build `cmsmon-hadoop-base` image in GH actions because it requires access to CERN internal network to get internal RPM packages. If there is solution for that I can apply but I think we build that image each 1-2 months manually when CERN releases new one each month.

So, how we can build those images: **via git tag messages**

For example:
- `git tag -a v00.03.01 -m "Build docker all with spark3-date=20220819"` will build all 3 images and push them to CERN registry
- `git tag -a v00.03.01 -m "Build docker (cmsmon-rucio-ds) with spark3-date=20220819"` will build only `cmsmon-rucio-ds`
- `git tag -a v00.03.01 -m "Build docker (cmsmon-rucio-spark2mng, condor-cpu-eff) with spark3-date=20220819"` will build mentioned 2 images, etc.

Git tag will be used as docker image tag of these images, thats why we need to continue to use `vXX.XX.XX` convention which is already set, or change it. See this image `registry.cern.ch/cmsmonitoring/condor-cpu-eff:v00.03.00` that build by GH actions.

### CODE REVIEW

**Comment by vkuznet** [comment]
@mrceyhun , there are several solutions which you may try to overcome CERN based package:
- you may build base image with required package and upload it to public repo like docker hub. Then, you can use this image to build you other CMS specific images. The caveat here is that you must insure that the image you upload to public repo should not contain any hard-coded credentials. Apart from that it is doable
- another solution, you may identify which RPM repo the hadoop comes from and add this repo config into your Dockerfile. If CERN publish there RPMs and the repo, then they should be publicly accessible. Check out `/etc/yum-puppet.repos.d` and you'll see all CERN repos. For RedHat (RPM) based images you only need to include proper repo to your Dockerfile.
- finally, you may decouple your image into 2, one will provide hadoop tools, and another only CMS code. Then, you can use side-case approach to mount some areas from your hadoop image to your desired one

Of course, it all depends how much effort you want to put into maintenance. To me, getting GitHub Action working comes with long-term benefits which will save the group the maintenance cost and put everything on auto-pilot.

**Comment by mrceyhun** [comment]
Thanks @vkuznet 
My initial goal is to get rid of all manual docker image builds (manual build tests took lots of my time this week). That's why I'll do it with any cost :) 

AFAIU, even in `yum update` command run, yum tries to connect http://linuxsoft.cern.ch/internal/yumsnapshot/20220801/epel/7/x86_64/repodata/repomd.xml. For external libraries, it skips 403 errors but for internal packages like epel java-1.8 that build by CERN, it exits with HTTP 403 error since there is no external alternative of it. I could not find any solution to it.

So, I think we can use `gitlab-registry.cern.ch/db/cerndb-infra-hadoop-conf:latest-hdp3` as base image. Hadoop team updates it regularly. Image size is bigger than ours but this is a working solution. We need to add `GITLAB_USERNAME` and `GITLAB_PASSWORD` secrets to CMSSpark repo since that image cannot be accessed without authentication. In my tests, I used my user&pass. If you agree with solution, do you have any suggestions about which user's credentials we should set in GH for CERN gitlab-registry?

All these images build by GH action:
```
- registry.cern.ch/cmsmonitoring/cmsmon-hadoop-base:spark3-20220821
- registry.cern.ch/cmsmonitoring/cmsmon-rucio-ds:v00.03.00
- registry.cern.ch/cmsmonitoring/cmsmon-rucio-spark2mng:v00.03.00
- registry.cern.ch/cmsmonitoring/condor-cpu-eff:v00.03.00
```

I explained everything in the README.md. Conditional GH job runs are entailed with the `needs` and `if` conditions.

**Comment by vkuznet** [comment]
I think you can send request to CERN IT to create a smaller base image with CMS requirements. Or, may be you can ask them about recipe (dependencies) which are required to build base image, and automate procedure to build such small image and upload it to  the registry.  Regarding credentials, the CMSSpark repo already has `CERN_LOGIN` and `CERN_TOKEN` which you should use.

**Comment by mrceyhun** [comment]
Thanks @vkuznet . According to your comment in https://github.com/dmwm/CMSKubernetes/pull/1189 , I updated GH workflow to build other images, I removed base image build. 
Now GH action supports 2 options:
```
git tag -a v00.03.01 -m "Build docker all" will build all 3 images and push them to CERN registry
git tag -a v00.03.01 -m "Build docker (cmsmon-rucio-spark2mng, condor-cpu-eff)" will build only mentioned 2 images
```

**Comment by mrceyhun** [comment]
If you find this PR ready, I need at least 1 approval to merge to obey the conventions :)

**Review by brij01 — COMMENTED** [review]
Thanks @mrceyhun , I see you've implemented all the comments on the MR. it looks okay to me if @vkuznet can confirm.

**Comment by vkuznet** [comment]
+1 from my side

**Comment by mrceyhun** [comment]
I would like to say that, this is one of the nicest things we've ever implemented :rocket:
All 3 images build parallel in GH workflow in less than 10mins. For development... wow. Individual image is ready to use in 5 minutes.

**Comment by vkuznet** [comment]
@mrceyhun I'm glad that you recognized the power of this approach. All repos I handle these days have GitHub Action builds, and yes I only press one button to build everything and deploy them to k8s. The maintenance cost is reduced to zero.

**Comment by mrceyhun** [comment]
> @mrceyhun I'm glad that you recognized the power of this approach. All repos I handle these days have GitHub Action builds, and yes I only press one button to build everything and deploy them to k8s. The maintenance cost is reduced to zero.

Thanks @vkuznet , it's all your inspiration. I can say that auto deploy is coming soon :)

**Pull request merged**
