### PR TITLE
capture valid and invalid data sets by removing requirement on valid files

### PR DESCRIPTION
**Pull request by davidlange6**
As discussed in Jira already, the dbs dumps currently only capture valid datasets. As we need to capture also historically useful but now invalid data sets, this is not sufficient. This PR is a proposal for improving this situation. I've removed the requirement on files being valid and added a field for the number of valid files.

Further enhances to consider:

- Capture invalid files only for invalid data sets. What I see is the dbsClient is that data sets that are not valid also have no valid files. This means its not possible to find the files that were valid before a dataset was changed to being invalid. However in Spark queries, as far as I can tell, d_is_dataset_valid is always 1. This does not match what I see in queries via the dbs client (I believe). Because of this, I don't see a way to improve - this looks like it affects 1% of data sets.

- Sum the file size of valid files as well as the number of them. This is so far beyond my abilities..

### CODE REVIEW

**Comment by vkuznet** [comment]
David, the changes seem fine to me, the only question I have is did you test them in spark job? I only asking to know if we can put it on vocms092 which will generate new dataframes.

**Comment by davidlange6** [comment]
I don’t think this change breaks any of my code.. But I don’t have an overview of the use cases..

On Sep 2, 2020, at 8:32 PM, Valentin Kuznetsov <notifications@github.com<mailto:notifications@github.com>> wrote:



David, the changes seem fine to me, the only question I have is did you test them in spark job? I only asking to know if we can put it on vocms092 which will generate new dataframes.

**Comment by vkuznet** [comment]
@cronosnull , could you please review this that we can decide if we'll put it on vocms092 node.

**Comment by cronosnull** [comment]
This will affect the popularity plots (a.k.a. Scrutiny plots), making then non-comparable with the ones in the previous years (because the sizes and number of events will include invalid files).
If this is not the desired outcome, we need to make to take a different way. Maybe grouping also by f_is_file_valid (instead of having a sum if valid files) will work better as we then can filter by valid files on the popularity scripts (while still having the values in the dataset for the invalid ones). Other alternative can be using only valid files to calculate the sizes and the event count (using a "when f_is_file_valid == 1" in the aggregation), and having a different set of columns to have the ones of the invalid files. Using the later, we don't need to modify the popularity scripts.  

The events count plot is not affected by this change as it queries directly the dbs datasets on hdfs. As far as I can tell only the popularity plots are affected.

**Comment by davidlange6** [comment]
On Sep 3, 2020, at 11:18 AM, Christian Ariza <notifications@github.com<mailto:notifications@github.com>> wrote:



This will affect the popularity plots (a.k.a. Scrutiny plots), making then non-comparable with the ones in the previous years (because the sizes and number of events will include invalid files).
If this is not the desired outcome, we need to make to take a different way. Maybe grouping also by f_is_file_valid (instead of having a sum if valid files) will work better as we then can filter by valid files on the popularity scripts (while still having the values in the dataset for the invalid ones). Other alternative can be using only valid files to calculate the sizes and the event count (using a "when f_is_file_valid == 1" in the aggregation), and having a different set of columns to have the ones of the invalid files. Using the later, we don't need to modify the popularity scripts.


The popularity stuff needs to capture formerly valid but not currently valid files. This change brings us much closer to that goal (fixing a ~10% effect of missing datasets for a ~1% effect of invalid files). We could do much better if the is_dataset_valid piece was working- but it doesn’t seem to be


The events count plot is not affected by this change as it queries directly the dbs datasets on hdfs. As far as I can tell only the popularity plots are affected.

**Comment by cronosnull** [comment]
@davidlange6, Perfect, in that case, I agree merging the change, and no further change seems to be required to the popularity scripts.

**Pull request merged**
