### PR TITLE
Refactor cmsspark python codes for python3.9+

### PR DESCRIPTION
**Pull request by mrceyhun**
- Refactored the Python code base for Python3.9+
- Fixed some py2/3 differences
- Improved doc-strings, file definitions and styling
- Moved Phedex codes to `degraded` folder. If you'll **green light**, I'll delete them too.
- Fixed and improved `imports`
- Add `requirements.py`

It can be good to change `OptionParser` to `click` because the latter one makes code and main functions more readable. It is important because I will refactor bash scripts, modify them to run in K8s.

If you've time, a review would be great.

### CODE REVIEW

**Review by vkuznet — APPROVED** [review]
Changes are fine with me even though review such large number of files is tedious process. I hope you used automation tool.

**Comment by mrceyhun** [comment]
> Changes are fine with me even though review such large number of files is tedious process. I hope you used automation tool.

Yes Valentin, I'm using a tool.

Update:
- This PR will be a big refactoring. That's why I'll not merge it before testing everything.
- Now added `utils/common_utils.sh` for all common operations in shell scripts.
- I will refactor all cron jobs and create new ones to be able to run them in Kubernetes.

Anyone welcome to comment on any part along the way. It will also include some design choices which mainly focus on to run scripts in K8s.

**Review by brij01 — COMMENTED** [review]
Reviewed changes. 
Couldn't notice anything unusual. 
Agree with keeping the Phedex codes to `degraded` folder for now, deletion to be handled in a separate PR. 
To be kept in DRAFT state for now (not merging) as more refactoring changes are being appended.

**Comment by mrceyhun** [comment]
@kyrylogy now it is merged, please rebase and resolve conflicts in the commits in your PRs. In any problem, please write to me and we can take a look together.

**Pull request merged**
